# Generated by Django 2.1.4 on 2018-12-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('detailAddress', models.CharField(max_length=256)),
                ('contactPhone', models.CharField(max_length=12)),
                ('star', models.IntegerField(default=5)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('serviceTime', models.CharField(default='08:00:00 - 18:00:00', max_length=50)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=5),
        ),
    ]
