# Generated by Django 2.1.4 on 2018-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='star',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
