# Generated by Django 2.1.4 on 2018-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181213_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='serviceTime',
            field=models.CharField(blank=True, default='08:00:00 - 18:00:00', max_length=50, null=True),
        ),
    ]
