# Generated by Django 2.1.4 on 2018-12-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goodsId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Goods')),
                ('storeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Store')),
            ],
        ),
    ]
