# Generated by Django 2.1.4 on 2018-12-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_storegoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegoods',
            name='goodsId',
            field=models.ForeignKey(db_column='goodsId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Goods'),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='storeId',
            field=models.ForeignKey(db_column='storeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Store'),
        ),
    ]
