# Generated by Django 2.1.4 on 2018-12-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storegoods',
            name='goodsId',
        ),
        migrations.RemoveField(
            model_name='storegoods',
            name='storeId',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreGoods',
        ),
    ]
