# Generated by Django 2.1.4 on 2018-12-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('detailAddress', models.CharField(max_length=256)),
                ('contactPhone', models.CharField(max_length=12)),
                ('star', models.IntegerField(blank=True, default=5, null=True)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('serviceTime', models.CharField(blank=True, default='08:00:00 - 18:00:00', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='Goods',
            field=models.ManyToManyField(through='order.StoreGoods', to='order.Goods'),
        ),
    ]
