# Generated by Django 2.1.4 on 2018-12-20 03:23

from django.db import migrations, models
import django.db.models.deletion


def insert_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("user", "User")
    user = User(id=0, openid='n/a', nickname='')
    user.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.RunPython(insert_user),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('detailAddress', models.CharField(blank=True, max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('editTime', models.DateTimeField(auto_now=True)),
                ('payTime', models.DateTimeField(blank=True, null=True)),
                ('acceptTime', models.DateTimeField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('ship', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10)),
                ('status', models.SmallIntegerField(default=0)),
                ('courier',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courier',
                                   to='user.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('detailAddress', models.CharField(blank=True, max_length=256)),
                ('contactPhone', models.CharField(max_length=12)),
                ('star', models.IntegerField(blank=True, default=5, null=True)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('serviceTime', models.CharField(blank=True, default='08:00:00 - 18:00:00', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('good',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='order.Goods')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_goods',
                                            to='order.Store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='goods',
            field=models.ManyToManyField(through='order.StoreGoods', to='order.Goods'),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='order.Order'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Store'),
        ),
    ]
