# Generated by Django 2.1.4 on 2018-12-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Goods',
            new_name='goods',
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_goods', to='order.Store'),
        ),
    ]
