# Generated by Django 2.1.4 on 2018-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181213_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
