# Generated by Django 2.1.4 on 2018-12-14 04:15

from django.db import migrations, models
import django.db.models.deletion


def insert_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("user", "User")
    user = User(id=0, openid='n/a', nickname='')
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0013_user_verified'),
        ('order', '0007_auto_20181213_1341'),
    ]

    operations = [
        migrations.RunPython(insert_user),
        migrations.AddField(
            model_name='order',
            name='acceptTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courier',
                                    to='user.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='finishTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
