# Generated by Django 2.1.4 on 2018-12-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20181214_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='detailAddress',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
